import { JobPosting } from '../types';

export const DUMMY_JOBS: JobPosting[] = [
  {
    id: 'job-1',
    employerId: 'user-2',
    title: 'Senior Backend Developer',
    description: 'NestJS-based backend service development. Microservice architecture design and implementation.',
    requiredSkills: ['TypeScript', 'NestJS', 'PostgreSQL'],
    preferredSkills: ['Docker', 'Kubernetes', 'Redis'],
    salaryMin: 60000000,
    salaryMax: 80000000,
    remotePolicy: '3 days in office',
    workingHours: '09:00-18:00 flexible',
    benefits: 'Stock options, Lunch support, Education budget',
    status: 'ACTIVE',
    negotiationBoundary: {
      salaryMin: 60000000,
      salaryMax: 75000000,
      salaryHardMax: 85000000,
      remotePolicyOptions: ['3 days office', '2 days office', 'Full remote'],
      nonNegotiableItems: ['3 month probation'],
      flexibleItems: ['Start date', 'Remote ratio', 'Signing bonus'],
      negotiationStyle: 'moderate',
    },
  },
  {
    id: 'job-2',
    employerId: 'user-2',
    title: 'Full-stack Developer',
    description: 'React + NestJS full-stack development. New service MVP.',
    requiredSkills: ['React', 'TypeScript', 'Node.js'],
    preferredSkills: ['Next.js', 'GraphQL'],
    salaryMin: 55000000,
    salaryMax: 70000000,
    remotePolicy: 'Full remote',
    workingHours: 'Flexible',
    benefits: 'Stock options, Remote equipment support',
    status: 'ACTIVE',
    negotiationBoundary: null,
  },
  {
    id: 'job-3',
    employerId: 'user-2',
    title: 'DevOps Engineer',
    description: 'Kubernetes cluster management. CI/CD pipeline construction.',
    requiredSkills: ['Kubernetes', 'Docker', 'AWS'],
    preferredSkills: ['Terraform', 'Go'],
    salaryMin: 65000000,
    salaryMax: 85000000,
    remotePolicy: '2 days in office',
    workingHours: '09:00-18:00',
    benefits: 'Stock options, AWS certification support',
    status: 'ACTIVE',
    negotiationBoundary: null,
  },
];
